apiVersion: v1
kind: Pod
metadata:
  name: manual-debug-pod
spec:
  containers:
  - name: shell
    image: registry.redhat.io/rhoai/odh-data-science-pipelines-argo-argoexec-rhel9@sha256:c147c123deabb49b4c974abb21c80b4ddbad076a45e4a248c41c2b48a1f05e5e
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: data-volume
      mountPath: /mnt/data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: ingestion-pvc
