FROM registry.redhat.io/rhoai/odh-pipeline-runtime-minimal-cpu-py312-rhel9:v3.2
COPY pyproject.toml uv.lock ./

RUN uv export --format requirements.txt --no-dev --frozen -o requirements.txt
RUN pip install --no-cache-dir -r requirements.txt