---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  labels:
    app: pgsql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  labels:
    app: pgsql
type: Opaque
stringData:
  POSTGRESQL_DATABASE: db
  POSTGRESQL_USER: pguser
  POSTGRESQL_PASSWORD: secret1!
  POSTGRESQL_ADMIN_PASSWORD: admin1!

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  labels:
    app: pgsql
    app.openshift.io/runtime: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pgsql
  template:
    metadata:
      labels:
        name: pgsql
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: pg-secret
          image: registry.redhat.io/rhel10/postgresql-16:10.1
          name: pgsql
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 32Mi
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/pgsql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pg-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  labels:
    app: pgsql
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: pgsql
  type: ClusterIP